# Application settings
app_name: barphani-crm-frontend
app_port: 8004
health_check_path: "/"
env: production

# Domain configuration
domain: barphani.vasifytech.com

# Target machine (must match inventory.yml)
target_host: production

# SSL settings
ssl_email: yogendra@vasifytech.com

# Docker registry (GitLab)
registry: registry.gitlab.com
registry_image: registry.gitlab.com/vasify/vasify-docker-registry
